<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    
    <xacro:include filename="robot_params.xacro"/>

    <joint name="laser_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_link"/>
        <origin xyz="${chassis_length/2} 0 ${chassis_height + laser_length/2}" rpy="0 0 0"/>
    </joint>

    <link name="laser_link">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${laser_mass}" length="${laser_length}" radius="${laser_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>



    <gazebo reference="laser_link">
        <material>Gazebo/Red</material>

        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>false</visualize>
            <update_rate>${laser_update_rate}</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>${laser_samples}</samples>
                        <min_angle>${laser_min_angle}</min_angle>
                        <max_angle>${laser_max_angle}</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>${laser_min_range}</min>
                    <max>${laser_max_range}</max>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>${laser_noise_mean}</mean>
                    <stddev>${laser_noise_stddev}</stddev>
                </noise>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <remapping>~/out:=scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>