<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- PARAMETERS -->

    <!-- Robot Physical Dimensions -->
    <xacro:property name="chassis_length" value="0.3"/>
    <xacro:property name="chassis_width" value="0.3"/>
    <xacro:property name="chassis_height" value="0.15"/>
    <xacro:property name="chassis_mass" value="0.5"/>

    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_diameter" value="${wheel_radius * 2}"/>
    <xacro:property name="wheel_thickness" value="0.04"/>
    <xacro:property name="wheel_offset_x" value="0.1"/>
    <xacro:property name="wheel_offset_y" value="0.175"/>
    <xacro:property name="wheel_separation" value="${wheel_offset_y * 2}"/>

    <xacro:property name="caster_wheel_offset_x" value="0.24"/>
    <xacro:property name="caster_wheel_radius" value="0.05"/>
    <xacro:property name="caster_wheel_mass" value="0.1"/>

    <!-- LiDAR Parameters -->
    <xacro:property name="laser_mass" value="0.1"/>
    <xacro:property name="laser_length" value="0.04"/>
    <xacro:property name="laser_radius" value="0.05"/>
    <xacro:property name="laser_update_rate" value="5"/>
    <xacro:property name="laser_samples" value="360"/>
    <xacro:property name="laser_min_angle" value="-3.14"/>
    <xacro:property name="laser_max_angle" value="3.14"/>
    <xacro:property name="laser_min_range" value="0.2"/>
    <xacro:property name="laser_max_range" value="12"/>
    <xacro:property name="laser_noise_mean" value="0.0"/>
    <xacro:property name="laser_noise_stddev" value="0.01"/>

    <!-- Camera Parameters -->
    <xacro:property name="camera_mass" value="0.03"/>
    <xacro:property name="camera_length" value="0.01"/>
    <xacro:property name="camera_width" value="0.03"/>
    <xacro:property name="camera_height" value="0.03"/>
    <xacro:property name="camera_update_rate" value="5"/>
    <xacro:property name="camera_horizontal_fov" value="1.089"/>
    <xacro:property name="camera_image_width" value="640"/>
    <xacro:property name="camera_image_height" value="480"/>
    <xacro:property name="camera_clip_near" value="0.05"/>
    <xacro:property name="camera_clip_far" value="8.0"/>


    <!-- GPS Parameters -->
    <xacro:property name="gps_mass" value="0.05"/>
    <xacro:property name="gps_update_rate" value="1"/>
    <xacro:property name="gps_noise_stddev" value="0.01"/>
    
    <!-- IMU Parameters -->
    <xacro:property name="imu_mass" value="0.05"/>
    <xacro:property name="imu_update_rate" value="200"/>
    <xacro:property name="imu_angular_velocity_stddev" value="2e-4"/>
    <xacro:property name="imu_linear_acceleration_stddev" value="1.7e-2"/>
    
</robot>